### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by lancecarlson** [williamkapke/allow#1]
This is an awesome project!! Do you know what the browser compatibility is?

**Comment by williamkapke** [comment]
Thanks! I know some have browserify'd and are using it. Since it references `__proto__` it requires IE11+
All other modern browsers should be fine- but I have not tested them.

**Comment by lancecarlson** [comment]
Ah crap. Would it be a huge overhaul to get it at least ie8+ compatible?

(and yes I just got it working using browserify but have only been testing with latest version of chrome)

**Comment by williamkapke** [comment]
I removed the usages of `__proto__` in 517785b651d92a386dc99986e05979b8fdfa7f95 which should make it compatible with IE9+.

I think IE8 will just need a polyfill for Object.keys.

**Comment by lancecarlson** [comment]
Boom! Saweet!
